#ifndef CONFIG_H
#define CONFIG_H

// Correspond to consts in kernel.asm
#define KERNEL_CODE_SELECTOR 0x08 // CODE_SEG equ 0x08
#define KERNEL_DATA_SELECTOR 0x10 // DATA_SEG equ 0x10


#define LILOS_TOTAL_INTERRUPTS 512

// 100 MB heap size
#define LILOS_HEAP_SIZE_BYTES 104857600
#define LILOS_HEAP_BLOCK_SIZE 4096
#define LILOS_HEAP_ADDRESS 0x01000000
#define LILOS_HEAP_TABLE_ADDRESS 0x00007E00

#define LILOS_SECTOR_SIZE 512

#define LILOS_MAX_FILESYSTEMS 12
#define LILOS_MAX_FILE_DESCRIPTORS 512

#define LILOS_MAX_PATH 108

#define LILOS_TOTAL_GDT_SEGMENTS 6

// All user programs are mapped to this address
#define LILOS_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define LILOS_USER_PROGRAM_STACK_SIZE 1024 * 16
#define LILOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define LILOS_PROGRAM_VIRTUAL_STACK_ADDRESS_END LILOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START - LILOS_USER_PROGRAM_STACK_SIZE

#define LILOS_MAX_PROGRAM_ALLOCATIONS 1024
#define LILOS_MAX_PROCESSES 12

#define USER_DATA_SEGMENT 0x23
#define USER_CODE_SEGMENT 0x1b

#define LILOS_MAX_ISR80H_COMMANDS 1024

#define LILOS_KEYBOARD_BUFFER_SIZE 1024

#endif